theme: jekyll-theme-architect
title: AM205 2017 Fall Project
description: 2D Pattern Formation with Reaction Diffusion Equations
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
