theme: jekyll-theme-architect
title: AM205 2017 Fall Project 2D Pattern
description: Formation with Reaction Diffusion Equations
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
